- name: apps
  become: true
  block:
    - name: Create traefik_network
      community.docker.docker_network:
        name: traefik_network
      register: n_output
    - name: Debug output
      ansible.builtin.debug:
        var: n_output
    - name: Create a Directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME_DIR') }}/{{ lookup('ansible.builtin.env', 'PROJECT_DIR') }}/appflowy"
        state: directory
    - name: Stop container if exists
      docker_container:
        name: "api-gateway"
        state: absent
        force_kill: true
    - name: Ensure destination directory exists with correct permissions
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME_DIR') }}/{{ lookup('ansible.builtin.env', 'PROJECT_DIR') }}/appflowy"
        state: directory
        mode: '0755'
      become: true
    - name: Sync entire project (with minimal preservation)
      ansible.builtin.synchronize:
        src: "{{ playbook_dir | dirname | dirname }}/"
        dest: "{{ lookup('ansible.builtin.env', 'HOME_DIR') }}/{{ lookup('ansible.builtin.env', 'PROJECT_DIR') }}/appflowy/"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"
          - "--exclude=.github"
          - "--no-perms"
          - "--no-owner"
          - "--no-group"
          - "--no-times"
          - "--recursive"
          - "--links"
        archive: false
        use_ssh_args: true
      become: false
    - name: Run docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ lookup('ansible.builtin.env', 'HOME_DIR') }}/{{ lookup('ansible.builtin.env', 'PROJECT_DIR') }}/appflowy"
        pull: always
      register: output
    - name: Debug output
      ansible.builtin.debug:
        var: output

